name: Build & Deploy pygbag

on:
  push:
    branches: [main]
    paths:  # Executa apenas quando arquivos relevantes mudam
      - '**.py'
      - '!README.md'
      - '!**.txt'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  web:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Previne execuções infinitas
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Importante para o pygbag
          
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'  # Cache para instalações mais rápidas
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygbag
      
      - name: Build project
        run: pygbag --build --cache /tmp/pygbag_cache .  # Cache para builds
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GEOREIGNS_SECRET }}
          publish_dir: ./build/web
          force_orphan: true
          keep_files: false  # Limpa deploy anterior
          commit_message: 'Deploy: ${{ github.sha }}'  # Mensagem informativa